"""add cover crop data table

Revision ID: 5175121ef5aa
Revises: fdc61a8e5f29
Create Date: 2024-11-22 19:53:53.211601+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5175121ef5aa"
down_revision = "fdc61a8e5f29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cover_crop_data",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sampling_date", sa.Date(), nullable=False),
        sa.Column("observed_cover_crop_biomass", sa.Float(), nullable=True),
        sa.Column("predicted_cover_crop_biomass", sa.Float(), nullable=True),
        sa.Column("cover_crop_biomass_unit", sa.String(length=50), nullable=True),
        sa.Column("observed_CN_ratio", sa.Float(), nullable=True),
        sa.Column("predicted_CN_ratio", sa.Float(), nullable=True),
        sa.Column(
            "cover_crop_data_ref_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cover_crop_data_ref_id"],
            ["cover_crop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("cover_crop", "sampling_date")
    op.drop_column("cover_crop", "predicted_cover_crop_biomass")
    op.drop_column("cover_crop", "predicted_CN_ratio")
    op.drop_column("cover_crop", "cover_crop_biomass_unit")
    op.drop_column("cover_crop", "observed_CN_ratio")
    op.drop_column("cover_crop", "observed_cover_crop_biomass")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cover_crop",
        sa.Column(
            "observed_cover_crop_biomass",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cover_crop",
        sa.Column(
            "observed_CN_ratio",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cover_crop",
        sa.Column(
            "cover_crop_biomass_unit",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cover_crop",
        sa.Column(
            "predicted_CN_ratio",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cover_crop",
        sa.Column(
            "predicted_cover_crop_biomass",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cover_crop",
        sa.Column("sampling_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.drop_table("cover_crop_data")
    # ### end Alembic commands ###
