"""add more fields in research table

Revision ID: 3460305f5ebe
Revises: 8ebfae34199a
Create Date: 2024-11-14 19:48:28.058383+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3460305f5ebe"
down_revision = "8ebfae34199a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research", sa.Column("research_pi", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "research",
        sa.Column("research_contact_info", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "research",
        sa.Column("research_introduction", sa.String(length=400), nullable=True),
    )
    op.add_column(
        "research",
        sa.Column("research_conclusion", sa.String(length=400), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research", "research_conclusion")
    op.drop_column("research", "research_introduction")
    op.drop_column("research", "research_contact_info")
    op.drop_column("research", "research_pi")
    # ### end Alembic commands ###
